import 'package:flutter/foundation.dart';
import 'question.dart';

enum LessonStatus { idle, inProgress, completed, abandoned }

@immutable
class Lesson {
  const Lesson({
    required this.id,
    required this.title,
    required this.description,
    required this.courseLanguage,
    required this.cefrLevel,
    required this.skillTag,
    required this.questions,
    this.estimatedMinutes = 5,
    this.xpReward = 30,
  });

  final String id;
  final String title;
  final String description;
  final String courseLanguage;  // ISO 639-1, e.g. "es"
  final String cefrLevel;
  final String skillTag;
  final List<Question> questions;
  final int estimatedMinutes;
  final int xpReward;

  bool get isAiGenerated => id.startsWith('ai-');
}

@immutable
class ChatMessage {
  const ChatMessage({
    required this.id,
    required this.role,
    required this.text,
    required this.timestamp,
  });

  final String id;
  final ChatRole role;
  final String text;
  final DateTime timestamp;
}

enum ChatRole { user, assistant }

// ---------------------------------------------------------------------------
// Seed data — used until the backend lesson API is wired up.
// ---------------------------------------------------------------------------
final kLessonsByLanguage = <String, List<Lesson>>{
  'es': [
    Lesson(
      id:             'es-A2-present-tense-04',
      title:          'Present Tense',
      description:    'Conjugate regular -AR verbs in everyday sentences.',
      courseLanguage: 'es',
      cefrLevel:      'A2',
      skillTag:       'grammar/verb-conjugation',
      estimatedMinutes: 5,
      xpReward:       45,
      questions: const [
        MultipleChoiceQuestion(
          id:           'q1',
          lessonId:     'es-A2-present-tense-04',
          cefrLevel:    'A2',
          skillTag:     'grammar/verb-conjugation',
          prompt:       'Which sentence is correct?',
          options: [
            'Ella habla español muy bien.',
            'Ella hablar español muy bien.',
            'Ella hablamos español muy bien.',
            'Ella hablo español muy bien.',
          ],
          correctIndex: 0,
          hintText:     'Third person singular -AR: drop -ar, add -a.',
        ),
        MultipleChoiceQuestion(
          id:           'q2',
          lessonId:     'es-A2-present-tense-04',
          cefrLevel:    'A2',
          skillTag:     'grammar/verb-conjugation',
          prompt:       '"We work every day" in Spanish is…',
          options: [
            'Trabajamos todos los días.',
            'Trabajan todos los días.',
            'Trabajáis todos los días.',
            'Trabajo todos los días.',
          ],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id:           'q3',
          lessonId:     'es-A2-present-tense-04',
          cefrLevel:    'A2',
          skillTag:     'grammar/sentence-structure',
          prompt:       'Arrange the words to form a correct sentence.',
          shuffledWords: ['café', 'Yo', 'tomo', 'por', 'la', 'mañana'],
          correctOrder:  [1, 2, 0, 3, 4, 5],
        ),
        MultipleChoiceQuestion(
          id:           'q4',
          lessonId:     'es-A2-present-tense-04',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/daily-life',
          prompt:       'What does "vivir" mean?',
          options: ['to live', 'to leave', 'to love', 'to give'],
          correctIndex: 0,
        ),
        SpeakingQuestion(
          id:           'q5',
          lessonId:     'es-A2-present-tense-04',
          cefrLevel:    'A2',
          skillTag:     'speaking/conversation',
          conversationContext:
              'You are a patient Spanish tutor. The student is A2 level. '
              'Keep corrections short and encouraging. Respond in English.',
          promptText:
              'Tell me one thing you do every morning — in Spanish!',
          hintText: 'Try: "Yo ___ todos los días."',
        ),
      ],
    ),
    Lesson(
      id:             'es-A2-numbers-01',
      title:          'Numbers & Time',
      description:    'Count and tell the time in Spanish.',
      courseLanguage: 'es',
      cefrLevel:      'A2',
      skillTag:       'vocabulary/numbers',
      estimatedMinutes: 5,
      xpReward:       40,
      questions: const [
        MultipleChoiceQuestion(
          id:           'q1',
          lessonId:     'es-A2-numbers-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/numbers',
          prompt:       '"Twenty-five" in Spanish is…',
          options: ['Veinticinco', 'Veintitrés', 'Veintiocho', 'Treinta'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id:           'q2',
          lessonId:     'es-A2-numbers-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/numbers',
          prompt:       'What time is "Son las tres"?',
          options: ['3:00', '13:00', '3:30', '2:00'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id:           'q3',
          lessonId:     'es-A2-numbers-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/numbers',
          prompt:       'Arrange into a correct sentence.',
          shuffledWords: ['a', 'Voy', 'las', 'trabajo', 'ocho', 'al'],
          correctOrder:  [1, 0, 5, 4, 3, 2],
        ),
        MultipleChoiceQuestion(
          id:           'q4',
          lessonId:     'es-A2-numbers-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/numbers',
          prompt:       '"Fifty" in Spanish is…',
          options: ['Cincuenta', 'Cuarenta', 'Sesenta', 'Setenta'],
          correctIndex: 0,
        ),
      ],
    ),
    Lesson(
      id:             'es-A2-family-01',
      title:          'Family',
      description:    'Talk about your family in Spanish.',
      courseLanguage: 'es',
      cefrLevel:      'A2',
      skillTag:       'vocabulary/family',
      estimatedMinutes: 5,
      xpReward:       40,
      questions: const [
        MultipleChoiceQuestion(
          id:           'q1',
          lessonId:     'es-A2-family-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/family',
          prompt:       '"Mother" in Spanish is…',
          options: ['Madre', 'Hermana', 'Abuela', 'Tía'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id:           'q2',
          lessonId:     'es-A2-family-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/family',
          prompt:       '"Brother" in Spanish is…',
          options: ['Hermano', 'Padre', 'Abuelo', 'Hijo'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id:           'q3',
          lessonId:     'es-A2-family-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/family',
          prompt:       'Arrange into a correct sentence.',
          shuffledWords: ['hermanos', 'Tengo', 'dos'],
          correctOrder:  [1, 0, 2],
        ),
        MultipleChoiceQuestion(
          id:           'q4',
          lessonId:     'es-A2-family-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/family',
          prompt:       '"My grandmother" in Spanish is…',
          options: ['Mi abuela', 'Mi madre', 'Mi hermana', 'Mi tía'],
          correctIndex: 0,
        ),
      ],
    ),
    Lesson(
      id:             'es-A2-food-01',
      title:          'Food & Restaurant',
      description:    'Order food and talk about meals.',
      courseLanguage: 'es',
      cefrLevel:      'A2',
      skillTag:       'vocabulary/food',
      estimatedMinutes: 6,
      xpReward:       45,
      questions: const [
        MultipleChoiceQuestion(
          id:           'q1',
          lessonId:     'es-A2-food-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/food',
          prompt:       '"I would like a coffee" in Spanish is…',
          options: ['Quisiera un café', 'Quiero un té', 'Me gusta el café', 'Tomo agua'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id:           'q2',
          lessonId:     'es-A2-food-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/food',
          prompt:       '"The bill, please" in Spanish is…',
          options: ['La cuenta, por favor', 'El menú, por favor', 'Una mesa, por favor', 'El agua, por favor'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id:           'q3',
          lessonId:     'es-A2-food-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/food',
          prompt:       'Arrange into a correct sentence.',
          shuffledWords: ['hambre', 'Tengo', 'mucha'],
          correctOrder:  [1, 0, 2],
        ),
        MultipleChoiceQuestion(
          id:           'q4',
          lessonId:     'es-A2-food-01',
          cefrLevel:    'A2',
          skillTag:     'vocabulary/food',
          prompt:       '"Breakfast" in Spanish is…',
          options: ['Desayuno', 'Almuerzo', 'Cena', 'Merienda'],
          correctIndex: 0,
        ),
      ],
    ),
  ],
  'fr': [
    Lesson(
      id:               'fr-A1-greetings-01',
      title:            'Greetings',
      description:      'Learn basic French greetings and introductions.',
      courseLanguage:   'fr',
      cefrLevel:        'A1',
      skillTag:         'vocabulary/greetings',
      estimatedMinutes: 5,
      xpReward:         35,
      questions: const [
        MultipleChoiceQuestion(
          id: 'q1', lessonId: 'fr-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
          prompt: '"Hello" in French is…',
          options: ['Bonjour', 'Bonsoir', 'Au revoir', 'Merci'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id: 'q2', lessonId: 'fr-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
          prompt: '"Thank you" in French is…',
          options: ['Merci', 'S\'il vous plaît', 'Bonjour', 'De rien'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id: 'q3', lessonId: 'fr-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'grammar/sentence-structure',
          prompt: 'Arrange into a correct sentence.',
          shuffledWords: ['m\'appelle', 'Je', 'Marie'],
          correctOrder:  [1, 0, 2],
        ),
        MultipleChoiceQuestion(
          id: 'q4', lessonId: 'fr-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
          prompt: '"Goodbye" in French is…',
          options: ['Au revoir', 'Bonjour', 'Merci', 'Bonsoir'],
          correctIndex: 0,
        ),
      ],
    ),
    Lesson(
      id:               'fr-A1-numbers-01',
      title:            'Numbers',
      description:      'Count and use numbers in French.',
      courseLanguage:   'fr',
      cefrLevel:        'A1',
      skillTag:         'vocabulary/numbers',
      estimatedMinutes: 5,
      xpReward:         35,
      questions: const [
        MultipleChoiceQuestion(
          id: 'q1', lessonId: 'fr-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/numbers',
          prompt: '"Five" in French is…',
          options: ['Cinq', 'Six', 'Sept', 'Quatre'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id: 'q2', lessonId: 'fr-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/numbers',
          prompt: '"Twenty" in French is…',
          options: ['Vingt', 'Dix', 'Trente', 'Quinze'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id: 'q3', lessonId: 'fr-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'grammar/sentence-structure',
          prompt: 'Arrange into a correct sentence.',
          shuffledWords: ['ans', 'J\'ai', 'vingt'],
          correctOrder:  [1, 2, 0],
        ),
        MultipleChoiceQuestion(
          id: 'q4', lessonId: 'fr-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/numbers',
          prompt: '"How old are you?" in French is…',
          options: ['Quel âge as-tu?', 'Comment t\'appelles-tu?', 'Tu vas bien?', 'D\'où viens-tu?'],
          correctIndex: 0,
        ),
      ],
    ),
    Lesson(
      id:               'fr-A1-family-01',
      title:            'Family',
      description:      'Talk about your family in French.',
      courseLanguage:   'fr',
      cefrLevel:        'A1',
      skillTag:         'vocabulary/family',
      estimatedMinutes: 5,
      xpReward:         35,
      questions: const [
        MultipleChoiceQuestion(
          id: 'q1', lessonId: 'fr-A1-family-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/family',
          prompt: '"Mother" in French is…',
          options: ['Mère', 'Père', 'Sœur', 'Frère'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id: 'q2', lessonId: 'fr-A1-family-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/family',
          prompt: '"Brother" in French is…',
          options: ['Frère', 'Sœur', 'Père', 'Fils'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id: 'q3', lessonId: 'fr-A1-family-01',
          cefrLevel: 'A1', skillTag: 'grammar/sentence-structure',
          prompt: 'Arrange into a correct sentence.',
          shuffledWords: ['une', 'J\'ai', 'sœur'],
          correctOrder:  [1, 0, 2],
        ),
        MultipleChoiceQuestion(
          id: 'q4', lessonId: 'fr-A1-family-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/family',
          prompt: '"My father" in French is…',
          options: ['Mon père', 'Ma mère', 'Mon frère', 'Ma sœur'],
          correctIndex: 0,
        ),
      ],
    ),
  ],
  'de': [
    Lesson(
      id:               'de-A1-greetings-01',
      title:            'Greetings',
      description:      'Learn basic German greetings and introductions.',
      courseLanguage:   'de',
      cefrLevel:        'A1',
      skillTag:         'vocabulary/greetings',
      estimatedMinutes: 5,
      xpReward:         35,
      questions: const [
        MultipleChoiceQuestion(
          id: 'q1', lessonId: 'de-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
          prompt: '"Hello" in German is…',
          options: ['Hallo', 'Auf Wiedersehen', 'Danke', 'Bitte'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id: 'q2', lessonId: 'de-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
          prompt: '"Thank you" in German is…',
          options: ['Danke', 'Bitte', 'Hallo', 'Tschüs'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id: 'q3', lessonId: 'de-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'grammar/sentence-structure',
          prompt: 'Arrange into a correct sentence.',
          shuffledWords: ['heiße', 'Ich', 'Marie'],
          correctOrder:  [1, 0, 2],
        ),
        MultipleChoiceQuestion(
          id: 'q4', lessonId: 'de-A1-greetings-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
          prompt: '"Goodbye" in German is…',
          options: ['Auf Wiedersehen', 'Hallo', 'Danke', 'Guten Morgen'],
          correctIndex: 0,
        ),
      ],
    ),
    Lesson(
      id:               'de-A1-numbers-01',
      title:            'Numbers',
      description:      'Count and use numbers in German.',
      courseLanguage:   'de',
      cefrLevel:        'A1',
      skillTag:         'vocabulary/numbers',
      estimatedMinutes: 5,
      xpReward:         35,
      questions: const [
        MultipleChoiceQuestion(
          id: 'q1', lessonId: 'de-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/numbers',
          prompt: '"Five" in German is…',
          options: ['Fünf', 'Sechs', 'Sieben', 'Vier'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id: 'q2', lessonId: 'de-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/numbers',
          prompt: '"Twenty" in German is…',
          options: ['Zwanzig', 'Zehn', 'Dreißig', 'Fünfzehn'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id: 'q3', lessonId: 'de-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'grammar/sentence-structure',
          prompt: 'Arrange into a correct sentence.',
          shuffledWords: ['Jahre', 'Ich', 'zwanzig', 'bin', 'alt'],
          correctOrder:  [1, 3, 2, 0, 4],
        ),
        MultipleChoiceQuestion(
          id: 'q4', lessonId: 'de-A1-numbers-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/numbers',
          prompt: '"How old are you?" in German is…',
          options: ['Wie alt bist du?', 'Wie heißt du?', 'Woher kommst du?', 'Wie geht es dir?'],
          correctIndex: 0,
        ),
      ],
    ),
    Lesson(
      id:               'de-A1-daily-life-01',
      title:            'Daily Life',
      description:      'Essential German words for everyday situations.',
      courseLanguage:   'de',
      cefrLevel:        'A1',
      skillTag:         'vocabulary/daily-life',
      estimatedMinutes: 5,
      xpReward:         35,
      questions: const [
        MultipleChoiceQuestion(
          id: 'q1', lessonId: 'de-A1-daily-life-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/daily-life',
          prompt: '"Water" in German is…',
          options: ['Wasser', 'Brot', 'Milch', 'Kaffee'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id: 'q2', lessonId: 'de-A1-daily-life-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/daily-life',
          prompt: '"I am hungry" in German is…',
          options: ['Ich habe Hunger', 'Ich bin müde', 'Ich habe Durst', 'Ich bin krank'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id: 'q3', lessonId: 'de-A1-daily-life-01',
          cefrLevel: 'A1', skillTag: 'grammar/sentence-structure',
          prompt: 'Arrange into a correct sentence.',
          shuffledWords: ['Kaffee', 'Ich', 'trinke', 'jeden', 'Morgen'],
          correctOrder:  [1, 2, 0, 3, 4],
        ),
        MultipleChoiceQuestion(
          id: 'q4', lessonId: 'de-A1-daily-life-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/daily-life',
          prompt: '"Where is the toilet?" in German is…',
          options: ['Wo ist die Toilette?', 'Was kostet das?', 'Wie spät ist es?', 'Wo bin ich?'],
          correctIndex: 0,
        ),
      ],
    ),
    Lesson(
      id:               'de-A1-food-01',
      title:            'Food & Drink',
      description:      'Order food and drinks in German.',
      courseLanguage:   'de',
      cefrLevel:        'A1',
      skillTag:         'vocabulary/food',
      estimatedMinutes: 5,
      xpReward:         35,
      questions: const [
        MultipleChoiceQuestion(
          id: 'q1', lessonId: 'de-A1-food-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/food',
          prompt: '"Bread" in German is…',
          options: ['Brot', 'Käse', 'Wurst', 'Butter'],
          correctIndex: 0,
        ),
        MultipleChoiceQuestion(
          id: 'q2', lessonId: 'de-A1-food-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/food',
          prompt: '"I would like a beer" in German is…',
          options: ['Ich hätte gern ein Bier', 'Ich trinke Wein', 'Ein Kaffee bitte', 'Ich esse Wurst'],
          correctIndex: 0,
        ),
        WordOrderQuestion(
          id: 'q3', lessonId: 'de-A1-food-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/food',
          prompt: 'Arrange into a correct sentence.',
          shuffledWords: ['bitte', 'Die', 'Rechnung'],
          correctOrder:  [1, 2, 0],
        ),
        MultipleChoiceQuestion(
          id: 'q4', lessonId: 'de-A1-food-01',
          cefrLevel: 'A1', skillTag: 'vocabulary/food',
          prompt: '"Breakfast" in German is…',
          options: ['Frühstück', 'Mittagessen', 'Abendessen', 'Snack'],
          correctIndex: 0,
        ),
      ],
    ),
  ],
  'it': [
    Lesson(
      id: 'it-A1-greetings-01', title: 'Greetings', description: 'Learn basic Italian greetings.',
      courseLanguage: 'it', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'it-g1', lessonId:'it-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'Come si dice "Hello"?', options:['Ciao','Arrivederci','Grazie','Per favore'], correctIndex:0),
        MultipleChoiceQuestion(id:'it-g2', lessonId:'it-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'Cosa significa "Grazie"?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'it-g3', lessonId:'it-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'Come si dice "Yes"?', options:['No','Forse','Sì','Mai'], correctIndex:2),
        MultipleChoiceQuestion(id:'it-g4', lessonId:'it-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'Cosa significa "Arrivederci"?', options:['Hello','Thank you','Please','Goodbye'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'it-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Italian sentences.',
      courseLanguage: 'it', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'it-s1', lessonId:'it-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Scegli la forma corretta: "Io ___ italiano."', options:['parlo','parli','parla','parliamo'], correctIndex:0),
        MultipleChoiceQuestion(id:'it-s2', lessonId:'it-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Cosa significa "Mi chiamo Luca"?', options:['I am tired','My name is Luca','I like Luca','I call Luca'], correctIndex:1),
        WordOrderQuestion(id:'it-w1', lessonId:'it-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I speak Italian"', translation:'I speak Italian',
          shuffledWords:['italiano','Io','parlo'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'it-w2', lessonId:'it-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The cat is black"', translation:'The cat is black',
          shuffledWords:['nero','Il','è','gatto'], correctOrder:[1,3,2,0]),
      ],
    ),
  ],
  'pt': [
    Lesson(
      id: 'pt-A1-greetings-01', title: 'Greetings', description: 'Learn basic Portuguese greetings.',
      courseLanguage: 'pt', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'pt-g1', lessonId:'pt-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'Como se diz "Hello"?', options:['Olá','Tchau','Obrigado','Por favor'], correctIndex:0),
        MultipleChoiceQuestion(id:'pt-g2', lessonId:'pt-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'O que significa "Obrigado"?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'pt-g3', lessonId:'pt-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'Como se diz "Yes"?', options:['Não','Talvez','Sim','Nunca'], correctIndex:2),
        MultipleChoiceQuestion(id:'pt-g4', lessonId:'pt-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'O que significa "Tchau"?', options:['Hello','Thank you','Please','Goodbye'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'pt-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Portuguese sentences.',
      courseLanguage: 'pt', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'pt-s1', lessonId:'pt-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Escolha a forma correta: "Eu ___ português."', options:['falo','falas','fala','falamos'], correctIndex:0),
        MultipleChoiceQuestion(id:'pt-s2', lessonId:'pt-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'O que significa "Meu nome é João"?', options:['I am tired','My name is João','I like João','I call João'], correctIndex:1),
        WordOrderQuestion(id:'pt-w1', lessonId:'pt-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I speak Portuguese"', translation:'I speak Portuguese',
          shuffledWords:['português','Eu','falo'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'pt-w2', lessonId:'pt-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The water is cold"', translation:'The water is cold',
          shuffledWords:['fria','A','está','água'], correctOrder:[1,3,2,0]),
      ],
    ),
  ],
  'ja': [
    Lesson(
      id: 'ja-A1-greetings-01', title: 'Greetings', description: 'Learn basic Japanese greetings.',
      courseLanguage: 'ja', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'ja-g1', lessonId:'ja-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello" in Japanese?', options:['こんにちは','さようなら','ありがとう','すみません'], correctIndex:0),
        MultipleChoiceQuestion(id:'ja-g2', lessonId:'ja-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "ありがとう" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'ja-g3', lessonId:'ja-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Good morning"?', options:['こんばんは','こんにちは','おはようございます','さようなら'], correctIndex:2),
        MultipleChoiceQuestion(id:'ja-g4', lessonId:'ja-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "さようなら" mean?', options:['Hello','Thank you','Please','Goodbye'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'ja-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Japanese sentences.',
      courseLanguage: 'ja', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'ja-s1', lessonId:'ja-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose the correct form: "わたしは＿＿です" (I am a student)', options:['がくせい','せんせい','いしゃ','かいしゃいん'], correctIndex:0),
        MultipleChoiceQuestion(id:'ja-s2', lessonId:'ja-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "わたしのなまえはたろうです" mean?', options:['I am tired','My name is Taro','I like Taro','I call Taro'], correctIndex:1),
        WordOrderQuestion(id:'ja-w1', lessonId:'ja-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I eat sushi"', translation:'I eat sushi',
          shuffledWords:['たべます','わたしは','すしを'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'ja-w2', lessonId:'ja-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "Today is Monday"', translation:'Today is Monday',
          shuffledWords:['です','きょうは','げつようび'], correctOrder:[1,2,0]),
      ],
    ),
  ],
  'ko': [
    Lesson(
      id: 'ko-A1-greetings-01', title: 'Greetings', description: 'Learn basic Korean greetings.',
      courseLanguage: 'ko', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'ko-g1', lessonId:'ko-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['안녕하세요','안녕히 가세요','감사합니다','주세요'], correctIndex:0),
        MultipleChoiceQuestion(id:'ko-g2', lessonId:'ko-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "감사합니다" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'ko-g3', lessonId:'ko-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Goodbye" (to someone leaving)?', options:['안녕하세요','안녕히 가세요','감사합니다','네'], correctIndex:1),
        MultipleChoiceQuestion(id:'ko-g4', lessonId:'ko-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "네" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'ko-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Korean sentences.',
      courseLanguage: 'ko', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'ko-s1', lessonId:'ko-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "저는 학생___."', options:['이에요','있어요','해요','가요'], correctIndex:0),
        MultipleChoiceQuestion(id:'ko-s2', lessonId:'ko-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "제 이름은 지수예요" mean?', options:['I am tired','My name is Jisu','I like Jisu','I call Jisu'], correctIndex:1),
        WordOrderQuestion(id:'ko-w1', lessonId:'ko-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I eat rice"', translation:'I eat rice',
          shuffledWords:['먹어요','저는','밥을'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'ko-w2', lessonId:'ko-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The weather is good"', translation:'The weather is good',
          shuffledWords:['좋아요','날씨가'], correctOrder:[1,0]),
      ],
    ),
  ],
  'zh': [
    Lesson(
      id: 'zh-A1-greetings-01', title: 'Greetings', description: 'Learn basic Mandarin greetings.',
      courseLanguage: 'zh', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'zh-g1', lessonId:'zh-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['你好','再见','谢谢','请'], correctIndex:0),
        MultipleChoiceQuestion(id:'zh-g2', lessonId:'zh-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "谢谢" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'zh-g3', lessonId:'zh-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Good morning"?', options:['晚上好','你好','早上好','再见'], correctIndex:2),
        MultipleChoiceQuestion(id:'zh-g4', lessonId:'zh-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "再见" mean?', options:['Hello','Thank you','Please','Goodbye'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'zh-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Mandarin sentences.',
      courseLanguage: 'zh', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'zh-s1', lessonId:'zh-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "我___ 中文。" (I speak Chinese)', options:['说','吃','喝','写'], correctIndex:0),
        MultipleChoiceQuestion(id:'zh-s2', lessonId:'zh-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "我叫小明" mean?', options:['I am tired','My name is Xiaoming','I like Xiaoming','I call Xiaoming'], correctIndex:1),
        WordOrderQuestion(id:'zh-w1', lessonId:'zh-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I eat noodles"', translation:'I eat noodles',
          shuffledWords:['面条','我','吃'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'zh-w2', lessonId:'zh-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "Today is hot"', translation:'Today is hot',
          shuffledWords:['很热','今天'], correctOrder:[1,0]),
      ],
    ),
  ],
  'ar': [
    Lesson(
      id: 'ar-A1-greetings-01', title: 'Greetings', description: 'Learn basic Arabic greetings.',
      courseLanguage: 'ar', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'ar-g1', lessonId:'ar-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['مرحبا','مع السلامة','شكرا','من فضلك'], correctIndex:0),
        MultipleChoiceQuestion(id:'ar-g2', lessonId:'ar-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "شكرا" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'ar-g3', lessonId:'ar-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Good morning"?', options:['مساء الخير','مرحبا','صباح الخير','مع السلامة'], correctIndex:2),
        MultipleChoiceQuestion(id:'ar-g4', lessonId:'ar-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "نعم" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'ar-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Arabic sentences.',
      courseLanguage: 'ar', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'ar-s1', lessonId:'ar-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "أنا ___ العربية." (I speak Arabic)', options:['أتكلم','آكل','أشرب','أكتب'], correctIndex:0),
        MultipleChoiceQuestion(id:'ar-s2', lessonId:'ar-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "اسمي أحمد" mean?', options:['I am tired','My name is Ahmed','I like Ahmed','I call Ahmed'], correctIndex:1),
        WordOrderQuestion(id:'ar-w1', lessonId:'ar-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink water"', translation:'I drink water',
          shuffledWords:['الماء','أنا','أشرب'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'ar-w2', lessonId:'ar-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The sky is blue"', translation:'The sky is blue',
          shuffledWords:['أزرق','السماء'], correctOrder:[1,0]),
      ],
    ),
  ],
  'ru': [
    Lesson(
      id: 'ru-A1-greetings-01', title: 'Greetings', description: 'Learn basic Russian greetings.',
      courseLanguage: 'ru', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'ru-g1', lessonId:'ru-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Привет','До свидания','Спасибо','Пожалуйста'], correctIndex:0),
        MultipleChoiceQuestion(id:'ru-g2', lessonId:'ru-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Спасибо" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'ru-g3', lessonId:'ru-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Good morning"?', options:['Добрый вечер','Привет','Доброе утро','До свидания'], correctIndex:2),
        MultipleChoiceQuestion(id:'ru-g4', lessonId:'ru-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Да" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'ru-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Russian sentences.',
      courseLanguage: 'ru', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'ru-s1', lessonId:'ru-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Я ___ по-русски." (I speak Russian)', options:['говорю','ем','пью','пишу'], correctIndex:0),
        MultipleChoiceQuestion(id:'ru-s2', lessonId:'ru-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Меня зовут Иван" mean?', options:['I am tired','My name is Ivan','I like Ivan','I call Ivan'], correctIndex:1),
        WordOrderQuestion(id:'ru-w1', lessonId:'ru-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I read a book"', translation:'I read a book',
          shuffledWords:['книгу','Я','читаю'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'ru-w2', lessonId:'ru-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The weather is cold"', translation:'The weather is cold',
          shuffledWords:['холодная','Погода'], correctOrder:[1,0]),
      ],
    ),
  ],
  'nl': [
    Lesson(
      id: 'nl-A1-greetings-01', title: 'Greetings', description: 'Learn basic Dutch greetings.',
      courseLanguage: 'nl', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'nl-g1', lessonId:'nl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Hallo','Tot ziens','Dank je','Alsjeblieft'], correctIndex:0),
        MultipleChoiceQuestion(id:'nl-g2', lessonId:'nl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Dank je" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'nl-g3', lessonId:'nl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Goodbye"?', options:['Hallo','Ja','Tot ziens','Nee'], correctIndex:2),
        MultipleChoiceQuestion(id:'nl-g4', lessonId:'nl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Ja" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'nl-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Dutch sentences.',
      courseLanguage: 'nl', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'nl-s1', lessonId:'nl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Ik ___ Nederlands." (I speak Dutch)', options:['spreek','spreekt','spreken','sprak'], correctIndex:0),
        MultipleChoiceQuestion(id:'nl-s2', lessonId:'nl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Ik heet Emma" mean?', options:['I am tired','My name is Emma','I like Emma','I call Emma'], correctIndex:1),
        WordOrderQuestion(id:'nl-w1', lessonId:'nl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink coffee"', translation:'I drink coffee',
          shuffledWords:['koffie','Ik','drink'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'nl-w2', lessonId:'nl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The house is small"', translation:'The house is small',
          shuffledWords:['klein','Het','is','huis'], correctOrder:[1,3,2,0]),
      ],
    ),
  ],
  'sv': [
    Lesson(
      id: 'sv-A1-greetings-01', title: 'Greetings', description: 'Learn basic Swedish greetings.',
      courseLanguage: 'sv', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'sv-g1', lessonId:'sv-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Hej','Hejdå','Tack','Snälla'], correctIndex:0),
        MultipleChoiceQuestion(id:'sv-g2', lessonId:'sv-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Tack" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'sv-g3', lessonId:'sv-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Goodbye"?', options:['Hej','Ja','Hejdå','Nej'], correctIndex:2),
        MultipleChoiceQuestion(id:'sv-g4', lessonId:'sv-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Ja" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'sv-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Swedish sentences.',
      courseLanguage: 'sv', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'sv-s1', lessonId:'sv-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Jag ___ svenska." (I speak Swedish)', options:['talar','talar inte','talar du','talat'], correctIndex:0),
        MultipleChoiceQuestion(id:'sv-s2', lessonId:'sv-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Jag heter Lisa" mean?', options:['I am tired','My name is Lisa','I like Lisa','I call Lisa'], correctIndex:1),
        WordOrderQuestion(id:'sv-w1', lessonId:'sv-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink tea"', translation:'I drink tea',
          shuffledWords:['te','Jag','dricker'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'sv-w2', lessonId:'sv-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The snow is white"', translation:'The snow is white',
          shuffledWords:['vit','Snön','är'], correctOrder:[1,2,0]),
      ],
    ),
  ],
  'no': [
    Lesson(
      id: 'no-A1-greetings-01', title: 'Greetings', description: 'Learn basic Norwegian greetings.',
      courseLanguage: 'no', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'no-g1', lessonId:'no-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Hei','Ha det','Takk','Vær så snill'], correctIndex:0),
        MultipleChoiceQuestion(id:'no-g2', lessonId:'no-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Takk" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'no-g3', lessonId:'no-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Goodbye"?', options:['Hei','Ja','Ha det','Nei'], correctIndex:2),
        MultipleChoiceQuestion(id:'no-g4', lessonId:'no-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Ja" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'no-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Norwegian sentences.',
      courseLanguage: 'no', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'no-s1', lessonId:'no-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Jeg ___ norsk." (I speak Norwegian)', options:['snakker','snakker ikke','snakker du','snakket'], correctIndex:0),
        MultipleChoiceQuestion(id:'no-s2', lessonId:'no-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Jeg heter Ingrid" mean?', options:['I am tired','My name is Ingrid','I like Ingrid','I call Ingrid'], correctIndex:1),
        WordOrderQuestion(id:'no-w1', lessonId:'no-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I eat fish"', translation:'I eat fish',
          shuffledWords:['fisk','Jeg','spiser'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'no-w2', lessonId:'no-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The mountain is high"', translation:'The mountain is high',
          shuffledWords:['høyt','Fjellet','er'], correctOrder:[1,2,0]),
      ],
    ),
  ],
  'da': [
    Lesson(
      id: 'da-A1-greetings-01', title: 'Greetings', description: 'Learn basic Danish greetings.',
      courseLanguage: 'da', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'da-g1', lessonId:'da-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Hej','Farvel','Tak','Vær venlig'], correctIndex:0),
        MultipleChoiceQuestion(id:'da-g2', lessonId:'da-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Tak" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'da-g3', lessonId:'da-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Goodbye"?', options:['Hej','Ja','Farvel','Nej'], correctIndex:2),
        MultipleChoiceQuestion(id:'da-g4', lessonId:'da-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Ja" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'da-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Danish sentences.',
      courseLanguage: 'da', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'da-s1', lessonId:'da-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Jeg ___ dansk." (I speak Danish)', options:['taler','taler ikke','taler du','talte'], correctIndex:0),
        MultipleChoiceQuestion(id:'da-s2', lessonId:'da-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Jeg hedder Peter" mean?', options:['I am tired','My name is Peter','I like Peter','I call Peter'], correctIndex:1),
        WordOrderQuestion(id:'da-w1', lessonId:'da-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink milk"', translation:'I drink milk',
          shuffledWords:['mælk','Jeg','drikker'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'da-w2', lessonId:'da-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The dog is friendly"', translation:'The dog is friendly',
          shuffledWords:['venlig','Hunden','er'], correctOrder:[1,2,0]),
      ],
    ),
  ],
  'pl': [
    Lesson(
      id: 'pl-A1-greetings-01', title: 'Greetings', description: 'Learn basic Polish greetings.',
      courseLanguage: 'pl', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'pl-g1', lessonId:'pl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Cześć','Do widzenia','Dziękuję','Proszę'], correctIndex:0),
        MultipleChoiceQuestion(id:'pl-g2', lessonId:'pl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Dziękuję" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'pl-g3', lessonId:'pl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Goodbye"?', options:['Cześć','Tak','Do widzenia','Nie'], correctIndex:2),
        MultipleChoiceQuestion(id:'pl-g4', lessonId:'pl-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Tak" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'pl-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Polish sentences.',
      courseLanguage: 'pl', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'pl-s1', lessonId:'pl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Ja ___ po polsku." (I speak Polish)', options:['mówię','mówisz','mówi','mówimy'], correctIndex:0),
        MultipleChoiceQuestion(id:'pl-s2', lessonId:'pl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Nazywam się Anna" mean?', options:['I am tired','My name is Anna','I like Anna','I call Anna'], correctIndex:1),
        WordOrderQuestion(id:'pl-w1', lessonId:'pl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I read a book"', translation:'I read a book',
          shuffledWords:['książkę','Ja','czytam'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'pl-w2', lessonId:'pl-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The cat is small"', translation:'The cat is small',
          shuffledWords:['mały','Kot','jest'], correctOrder:[1,2,0]),
      ],
    ),
  ],
  'tr': [
    Lesson(
      id: 'tr-A1-greetings-01', title: 'Greetings', description: 'Learn basic Turkish greetings.',
      courseLanguage: 'tr', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'tr-g1', lessonId:'tr-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Merhaba','Güle güle','Teşekkürler','Lütfen'], correctIndex:0),
        MultipleChoiceQuestion(id:'tr-g2', lessonId:'tr-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Teşekkürler" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'tr-g3', lessonId:'tr-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Goodbye"?', options:['Merhaba','Evet','Güle güle','Hayır'], correctIndex:2),
        MultipleChoiceQuestion(id:'tr-g4', lessonId:'tr-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Evet" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'tr-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Turkish sentences.',
      courseLanguage: 'tr', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'tr-s1', lessonId:'tr-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Ben Türkçe ___." (I speak Turkish)', options:['konuşuyorum','yiyorum','içiyorum','yazıyorum'], correctIndex:0),
        MultipleChoiceQuestion(id:'tr-s2', lessonId:'tr-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Benim adım Ayşe" mean?', options:['I am tired','My name is Ayşe','I like Ayşe','I call Ayşe'], correctIndex:1),
        WordOrderQuestion(id:'tr-w1', lessonId:'tr-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink water"', translation:'I drink water',
          shuffledWords:['içiyorum','Ben','su'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'tr-w2', lessonId:'tr-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The city is beautiful"', translation:'The city is beautiful',
          shuffledWords:['güzel','Şehir'], correctOrder:[1,0]),
      ],
    ),
  ],
  'hi': [
    Lesson(
      id: 'hi-A1-greetings-01', title: 'Greetings', description: 'Learn basic Hindi greetings.',
      courseLanguage: 'hi', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'hi-g1', lessonId:'hi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['नमस्ते','अलविदा','धन्यवाद','कृपया'], correctIndex:0),
        MultipleChoiceQuestion(id:'hi-g2', lessonId:'hi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "धन्यवाद" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'hi-g3', lessonId:'hi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Yes"?', options:['नहीं','शायद','हाँ','कभी नहीं'], correctIndex:2),
        MultipleChoiceQuestion(id:'hi-g4', lessonId:'hi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "अलविदा" mean?', options:['Hello','Thank you','Please','Goodbye'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'hi-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Hindi sentences.',
      courseLanguage: 'hi', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'hi-s1', lessonId:'hi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "मैं हिंदी ___।" (I speak Hindi)', options:['बोलता हूँ','खाता हूँ','पीता हूँ','लिखता हूँ'], correctIndex:0),
        MultipleChoiceQuestion(id:'hi-s2', lessonId:'hi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "मेरा नाम राज है" mean?', options:['I am tired','My name is Raj','I like Raj','I call Raj'], correctIndex:1),
        WordOrderQuestion(id:'hi-w1', lessonId:'hi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink milk"', translation:'I drink milk',
          shuffledWords:['पीता हूँ','मैं','दूध'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'hi-w2', lessonId:'hi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The flower is red"', translation:'The flower is red',
          shuffledWords:['लाल है','फूल'], correctOrder:[1,0]),
      ],
    ),
  ],
  'el': [
    Lesson(
      id: 'el-A1-greetings-01', title: 'Greetings', description: 'Learn basic Greek greetings.',
      courseLanguage: 'el', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'el-g1', lessonId:'el-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Γεια σου','Αντίο','Ευχαριστώ','Παρακαλώ'], correctIndex:0),
        MultipleChoiceQuestion(id:'el-g2', lessonId:'el-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Ευχαριστώ" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'el-g3', lessonId:'el-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Good morning"?', options:['Καλησπέρα','Γεια σου','Καλημέρα','Αντίο'], correctIndex:2),
        MultipleChoiceQuestion(id:'el-g4', lessonId:'el-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Ναι" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'el-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Greek sentences.',
      courseLanguage: 'el', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'el-s1', lessonId:'el-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Εγώ ___ ελληνικά." (I speak Greek)', options:['μιλώ','τρώω','πίνω','γράφω'], correctIndex:0),
        MultipleChoiceQuestion(id:'el-s2', lessonId:'el-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Με λένε Νίκο" mean?', options:['I am tired','My name is Niko','I like Niko','I call Niko'], correctIndex:1),
        WordOrderQuestion(id:'el-w1', lessonId:'el-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink water"', translation:'I drink water',
          shuffledWords:['νερό','Εγώ','πίνω'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'el-w2', lessonId:'el-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The sea is blue"', translation:'The sea is blue',
          shuffledWords:['μπλε','Η θάλασσα','είναι'], correctOrder:[1,2,0]),
      ],
    ),
  ],
  'he': [
    Lesson(
      id: 'he-A1-greetings-01', title: 'Greetings', description: 'Learn basic Hebrew greetings.',
      courseLanguage: 'he', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'he-g1', lessonId:'he-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['שלום','להתראות','תודה','בבקשה'], correctIndex:0),
        MultipleChoiceQuestion(id:'he-g2', lessonId:'he-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "תודה" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'he-g3', lessonId:'he-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Good morning"?', options:['לילה טוב','שלום','בוקר טוב','להתראות'], correctIndex:2),
        MultipleChoiceQuestion(id:'he-g4', lessonId:'he-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "כן" mean?', options:['No','Thank you','Hello','Yes'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'he-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Hebrew sentences.',
      courseLanguage: 'he', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'he-s1', lessonId:'he-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "אני ___ עברית." (I speak Hebrew)', options:['מדבר','אוכל','שותה','כותב'], correctIndex:0),
        MultipleChoiceQuestion(id:'he-s2', lessonId:'he-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "קוראים לי דוד" mean?', options:['I am tired','My name is David','I like David','I call David'], correctIndex:1),
        WordOrderQuestion(id:'he-w1', lessonId:'he-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink water"', translation:'I drink water',
          shuffledWords:['מים','אני','שותה'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'he-w2', lessonId:'he-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The sky is clear"', translation:'The sky is clear',
          shuffledWords:['בהיר','השמיים'], correctOrder:[1,0]),
      ],
    ),
  ],
  'vi': [
    Lesson(
      id: 'vi-A1-greetings-01', title: 'Greetings', description: 'Learn basic Vietnamese greetings.',
      courseLanguage: 'vi', cefrLevel: 'A1', skillTag: 'vocabulary/greetings',
      xpReward: 30, estimatedMinutes: 3,
      questions: const [
        MultipleChoiceQuestion(id:'vi-g1', lessonId:'vi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Hello"?', options:['Xin chào','Tạm biệt','Cảm ơn','Làm ơn'], correctIndex:0),
        MultipleChoiceQuestion(id:'vi-g2', lessonId:'vi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Cảm ơn" mean?', options:['Please','Goodbye','Hello','Thank you'], correctIndex:3),
        MultipleChoiceQuestion(id:'vi-g3', lessonId:'vi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'How do you say "Yes"?', options:['Không','Có thể','Có','Không bao giờ'], correctIndex:2),
        MultipleChoiceQuestion(id:'vi-g4', lessonId:'vi-A1-greetings-01', cefrLevel:'A1', skillTag:'vocabulary/greetings',
          prompt:'What does "Tạm biệt" mean?', options:['Hello','Thank you','Please','Goodbye'], correctIndex:3),
      ],
    ),
    Lesson(
      id: 'vi-A2-sentences-01', title: 'Everyday Sentences', description: 'Build simple Vietnamese sentences.',
      courseLanguage: 'vi', cefrLevel: 'A2', skillTag: 'grammar/basic-verbs',
      xpReward: 40, estimatedMinutes: 4,
      questions: const [
        MultipleChoiceQuestion(id:'vi-s1', lessonId:'vi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Choose: "Tôi ___ tiếng Việt." (I speak Vietnamese)', options:['nói','ăn','uống','viết'], correctIndex:0),
        MultipleChoiceQuestion(id:'vi-s2', lessonId:'vi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'What does "Tên tôi là Lan" mean?', options:['I am tired','My name is Lan','I like Lan','I call Lan'], correctIndex:1),
        WordOrderQuestion(id:'vi-w1', lessonId:'vi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "I drink tea"', translation:'I drink tea',
          shuffledWords:['trà','Tôi','uống'], correctOrder:[1,2,0]),
        WordOrderQuestion(id:'vi-w2', lessonId:'vi-A2-sentences-01', cefrLevel:'A2', skillTag:'grammar/basic-verbs',
          prompt:'Arrange: "The river is long"', translation:'The river is long',
          shuffledWords:['dài','Sông'], correctOrder:[1,0]),
      ],
    ),
  ],
};

Lesson get kSeedLesson => kLessonsByLanguage['es']!.first;
